### ISSUE TITLE
Layout elements are missing in VPB

### ISSUE THREAD

**Issue by epiceuropean** [ThemeFuse/Unyson#1383]
I updated to Unyson 2.5.0 from 2.4.17. Other plugins were also updated at the same time. All elements in all three tabs of the VPB are missing.

![unyson no builder](https://cloud.githubusercontent.com/assets/2949568/14025062/2d6e6b06-f1ba-11e5-85be-45db7e0142be.jpg)

The div containing the tab information is getting its "display" property set when I click on a tab: e.g. clicking on "Layout Elements" makes that div's "display:block" from "display:none"

I've deactivated all the other plugins I could. Other installed plugins: BookingBug, Events Manager, Less & scss PHP Compilers, MailChimp for WordPress, Varnish HTTP Purge, Very Simple Event List, WooCommerce, WordPress Importer.

Clearly a pretty big issue for me, since I can't edit or create any pages while this bug persists.

**Comment by epiceuropean** [comment]
Update: Rolling back to 2.4.17 has solved the issue for me. No longer a huge priority, but still would like to know what happened.

Thank you.

**Comment by moldcraft** [comment]
Make sure the extensions are up-to-date, then do Ctrl+R in browser.

**Comment by epiceuropean** [comment]
I appreciate that you responded to my issue, but I already did the internet equivalent of "turn it off, and back on again."

**Comment by moldcraft** [comment]
Can you send me admin details to `moldcraft[at]email.com`?

**Comment by epiceuropean** [comment]
I cannot obtain permission to do that, sorry.

**Comment by moldcraft** [comment]
Try to delete the Unyson plugin and install it back.

**Comment by epiceuropean** [comment]
OK, will try tomorrow. Backup is recommended, I'm assuming, but will I need to recover any settings, posts, etc when I reinstall?

**Comment by moldcraft** [comment]
Reinstall doesn't affect db data.

**Comment by moldcraft** [comment]
@epiceuropean Have you solved this problem?

**Comment by epiceuropean** [comment]
Sorry! Been a crazy few days; haven't touched it yet, but 2.4.17 is working fine at the moment. I'll mark this as 'closed' for now, and will attempt to reproduce it. If I can reliably do so, we can continue this conversation. Fair?

**Comment by moldcraft** [comment]
You can write here any time you want

**Comment by epiceuropean** [comment]
I deleted Unyson and reinstalled it. No help. 

I've updated to WP 4.5.1 and The Core theme to 1.0.6 to try to fix this issue, and now we're even more borked:

![wp problems 1](https://cloud.githubusercontent.com/assets/2949568/14861447/e456bfc6-0c72-11e6-8465-b94cbb397261.png)
![wp problems 2](https://cloud.githubusercontent.com/assets/2949568/14861449/e9157ade-0c72-11e6-8938-31e04059b022.png)

(Note that these are with Unyson 2.4.17 installed, since 2.5.3 continues to have the same issue as before: no items in the layout, content, or media element tabs.)

Furthermore, now my homepage map is missing, and mega menu doesn't work -- it doesn't expand on hover, or appear at all on mobile. This behavior started before updating the theme, but I'm not sure if it was there before the WP upgrade. The Mega Menu extension is enabled.


My guess is that the mega-menu issue is being caused by this (copied from the console):
```
jquery.js?ver=1.12.3:2 Uncaught Error: Syntax error, unrecognized expression: a[href=#]
fa.error @ jquery.js?ver=1.12.3:2
fa.tokenize @ jquery.js?ver=1.12.3:2
fa.select @ jquery.js?ver=1.12.3:2
fa @ jquery.js?ver=1.12.3:2
n.fn.extend.find @ jquery.js?ver=1.12.3:2
a.fn.find @ jquery-migrate.min.js?ver=1.4.0:2
n.fn.init @ jquery.js?ver=1.12.3:2a.f
n.init @ jquery-migrate.min.js?ver=1.4.0:2
n @ jquery.js?ver=1.12.3:2
(anonymous function) @ general.js?ver=1.0.7:19
i @ jquery.js?ver=1.12.3:2
j.fireWith @ jquery.js?ver=1.12.3:2
n.extend.ready @ jquery.js?ver=1.12.3:2
K @ jquery.js?ver=1.12.3:2
```
Obviously, with js being minified, there's not too much to learn there, but clearly it's something with Font Awesome's rendering of the MM icon, which could cause the whole script to fail.

OK, that's a lot of stuff. How can I help you next?

**Comment by moldcraft** [comment]
On our side everything works fine. We also experienced the issues you show in screenshots, but these were fixed in latest versions of Unyson and TheCore theme.

Please disable all your plugins, maybe you have a Cache plugin activated.

**Comment by epiceuropean** [comment]
Nice catch! The mega-menu and map issues were indeed a caching problem.

However, the Visual Page Builder issues persist. I can see the content elements in 2.4.17, but not in 2.5.0 or 2.5.3. In all versions, I get "function (n){return o.call(this,n,m)}" instead of the Section title, and I can't edit any element at all, as shown in the photos above.

**Comment by moldcraft** [comment]
The fix for `function (n){return o.call(this,n,m)}` is in Builder, Shortcodes and PageBuilder extension. So make sure your extensions are up-to-date, then do hard refresh in browser

**Comment by epiceuropean** [comment]
Awesome. Deleting and re-downloading that, followed by the hard reset, seems to have fixed it!

I'm impressed with how easily you were able to solve this issue. 11/10 would break again
