### ISSUE TITLE
error on logout

### ISSUE THREAD

**Issue by Jimmyfix** [ThemeFuse/Unyson#1988]
Hi,

Yesterday I started to configure a new theme where Unyson is integrated and an important part. Everything seemed normal until I tried to logout of the controlpanel to reach the custom login-site.

When I hit hte logout button, the browser started spinning, and after a while it showed an error message:

"The page isn't redirecting properly"

"Firefox has detected that the server is redirecting the request for this address in a way that will never complete."

From now, this message (or similar) appears when trying to reach the site in all kinds of browser. It's impossible to reach the adminpanel also. 

So I've started to investigate this. I manually deactivated all the plugins by renaming them one by one. This stated that the problem was the Unyson plugin that comes along with the theme. By renaming this I was able to log in and to se the site by normal URL. When activating the plugin and then trying to log out - the problem started all over again.

So I did this:

1. Deactivated all the exstensions in Unyson (one by one) - No impact
2. Deactivated all the other plugins to see if there were any conflict with Unyson - No impact
3. Removed and installed a new version of Unyson - No impact
4. Deactivated and reactivateded the theme - No impact
4. Deactivated Unyson and the tried to logout - That worked fine

So this indicates that the Unyson plugin is causing some problems.

The new theme is installed in a subfolder on the same domain as our main site.
Wordpress version: 4.6.1 using child-theme

Please advise me to find a solution to this?

**Comment by Jimmyfix** [comment]
wp_debug is on and shows nada
The following plugins are installed: BuddyPress, EventOn, EventON - full cal, File Away and Wise Chat

**Comment by moldcraft** [comment]
Please try [this version](https://github.com/ThemeFuse/Unyson-Extensions-Approval/issues/258) a [similar problem](https://github.com/ThemeFuse/Unyson/issues/1986) was fixed

**Comment by Jimmyfix** [comment]
Hi,

downloaded the new version and uploaded the content to the Unyson folder
The problem persists - but there is now an error showing: "Please register option-types on 'fw_option_types_init' action"

**Comment by moldcraft** [comment]
Can you send me admin/ftp details to `moldcraft[at]email.com`?

**Comment by moldcraft** [comment]
Thank you for email, I will inspect the problem in 1-2 hours. I got to go now, sorry.

**Comment by moldcraft** [comment]
Not related to this issue, a theme problem:

![staticshot_09-09-2016_21-39-36](https://cloud.githubusercontent.com/assets/1475489/18398544/f3351ab0-76d5-11e6-8e5d-5ff657c2ba45.png)

----

I deactivated the theme and the site works. So please report this issue to theme author.

I would like to help but debugging via FTP is pain. On my localhost I can open the directory with my IDE and search in all files very quick, but via FTP it's not possible.

**Comment by moldcraft** [comment]
> there is now an error showing: "Please register option-types on 'fw_option_types_init' action"

Downgrade to Unyson 2.6.1 and it will disappear.
