### ISSUE TITLE
Failed to create tmp table _fwbk_****_commentmeta

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Unyson#2501]
I have tried to install demo content. but facing issue with this error.

I have open details error [with this](https://github.com/ThemeFuse/Unyson-Backups-Extension/blob/v2.0.10/includes/module/tasks/type/class-fw-ext-backups-task-type-db-restore.php#L432-L440)
And replace with this
```
if ( false === $wpdb->query( $sql ) ) {
    $fo = null;
    return new WP_Error(
        'tmp_table_create_fail',
        sprintf( __( 'Failed to create tmp table %s', 'fw' ), $tmp_table_name )
        . ' | wpdb->last_error: '. $wpdb->last_error
        . ' | SQL: '. $sql
    );
}
```

Here is now full error log

`Failed to create tmp table _fwbk_mL94q_commentmeta | wpdb->last_error: Table 'ml94q_commentmeta' already exists | SQL: CREATE TABLE `ml94q_commentmeta` ( `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0', `meta_key` varchar(255) DEFAULT NULL, `meta_value` longtext, PRIMARY KEY (`meta_id`), KEY `comment_id` (`comment_id`), KEY `meta_key` (`meta_key`(191)) ) ENGINE=InnoDB DEFAULT CHARSET=utf8`

What should I do now?

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/a0dc705c9c9333458dffecce28eea6e47e8218e6

**Comment by GheorgheP** [comment]
Try development version https://github.com/ThemeFuse/Unyson-Backups-Extension
This issue was already fixed, soon we will make a new version.

**Comment by Ataurr** [comment]
This is not resolved.

Still getting error
`Failed to insert row from line 5 into table _fwbk_mL94q_comments. Table 'informat_wordpress_5._fwbk_ml94q_comments' doesn't exist`

**Comment by GheorgheP** [comment]
What is this prefix `informat_wordpress_5`?

**Comment by Ataurr** [comment]
It's work after reinstalling the WordPress.
