### ISSUE TITLE
Issue with page builder

### ISSUE THREAD

**Issue by Kopp13** [ThemeFuse/Unyson#2764]
hi guys,

got an issue with page builder. Cant see my pages anymore.

when i desactivate it, it works : 
<img width="934" alt="capture d ecran 2017-08-17 a 17 47 45" src="https://user-images.githubusercontent.com/31105873/29421120-5502a888-8374-11e7-81be-d910378c91df.png">

but when extension is activated :
<img width="948" alt="capture d ecran 2017-08-17 a 17 49 45" src="https://user-images.githubusercontent.com/31105873/29421165-7b4b4342-8374-11e7-96c9-338baa6ed433.png">

Can u help me ? :)
Ty

**Comment by macxb** [comment]
I have the same problem after the update, i cant see the editor or the drag and drop editor


thank you

**Comment by danyj** [comment]
> after the update

what update ?

**Comment by danyj** [comment]
same bug https://github.com/ThemeFuse/Unyson/issues/2764

**Comment by macxb** [comment]
unyson updated
the the visual editor wouldn't work

**Comment by macxb** [comment]
the page options are the same nothing visible, maybe that is something to do with it.
just a thought

**Comment by akguthal** [comment]
was having this issue on 2.7.3, just updated to 2.7.4 and i'm still having this issue

**Comment by danyj** [comment]
same here updated to 2.7.4  same bug

**Comment by samirosman2** [comment]
same issue with theme : real property when I active page bulider everything stop I cannot change any thing on the page even i cannot update page  
before http://prntscr.com/g9p9f8
after active all stop http://prntscr.com/g9pam2

please help us

**Comment by danyj** [comment]
@everyone here , help is on the way ,

**Comment by fischb0ne** [comment]
Oh good. I'm having the same issue.

**Comment by andreiglingeanu** [comment]
The team is on it.

**Comment by samirosman2** [comment]
thanks @danyj  appreciate your update 💯

**Comment by samirosman2** [comment]
thanks @andreiglingeanu

**Comment by alexluncashu** [comment]
Sorry guys for this mistake. We'll get back to stable version and fix this asap.

**Comment by macxb** [comment]
thanks its a great feature and I was nearly crying when it wouldn´t work ;)

**Comment by motormindzinc** [comment]
Just ringing in same thing - thank you for addressing it. My extranet peeps give you thumbs up.

**Comment by mtmcgreg** [comment]
Same thing for me, the editor just disappeared!

**Comment by akguthal** [comment]
updated to 2.7.5, still having the issue

**Comment by danyj** [comment]
everyone update , new 2.7.5 is out ,  I just did , 


@akguthal   shift + refresh

**Comment by danyj** [comment]
@akguthal ,   extensions are updated , it will take few minutes to see these in backend , they all need updates , 

theme admin works now

**Comment by akguthal** [comment]
hmm okay my theme admin still isnt working (after shift-refreshing) but i'll wait on it and let you know

**Comment by arielzusya** [comment]
How long should it take for the extension updates to populate? The only one I've seen come through since updating to 2.7.5 was sidebar.

**Comment by Becca800** [comment]
Installed 2.7.5, refreshed, theme customizer still not working.

**Comment by GheorgheP** [comment]
In short time will appear the extensions new versions, they should solve the problem

**Comment by arielzusya** [comment]
page builder extension just updated. Did a forced refresh. No change.

**Comment by Becca800** [comment]
Just worth mentioning, I deactivated all unyson extensions and I still can't use the customizer. Most of the elements in theme customizer are blank when expanded.

**Comment by arielzusya** [comment]
Was able to get to the old visual editor by disabling page builder. Then shortcode extension updated and now I cannot get to the text editor. Disabling shortcode fixed that. These updates do not seem to be fixing anything.

**Comment by andreiglingeanu** [comment]
Hold on guys. A new update is comming.

**Comment by alexluncashu** [comment]
#2770
#2769

**Comment by indopixel** [comment]
Hi guys,

I've been trying to solve this issue by deleting the Unyson plugin and do a fresh install with Unyson 2.7.5 that I downloaded from GitHub. Then my problem with **fw-reactive-options-registry.js Not Found** is gone.

**Comment by andreiglingeanu** [comment]
Hey @indopixel, yes, this problem is specific to the code deployed on the wordpress.org website. It will be fixed in the next half hour. Feel free to use GitHub of the Unyson, it is equally stable.

**Comment by Becca800** [comment]
Cool. That worked for me.

**Comment by andreiglingeanu** [comment]
The new 2.7.6 release is out and you'll soon have on your WordPress updates page. We are good!

**Comment by danyj** [comment]
all set on my end 

2.7.6 

theme admin 
page builder 

no errors so far.

**Comment by akguthal** [comment]
Okay so the pagebuilder is back and I'm not getting any errors in the console, but I can't see any of the elements in my editor that should be there (if I click "Preview Changes" everything shows up on the page fine). Any ideas?
![screenshot from 2017-08-17 15-21-30](https://user-images.githubusercontent.com/11077789/29429766-c574fc34-835f-11e7-87bc-239e02782fe4.png)

**Comment by mtmcgreg** [comment]
My visual page editor is still not working correctly.

**Comment by robinamoore** [comment]
If I try to edit an existing page on my website, the page-builder part is empty (in the back-end). Page looks fine on the front-end, so information appears stored.

If I duplicate a page, I can then edit the new page.

**Comment by danyj** [comment]
@akguthal **can't** confirm ,  I tested my existing pages and they look ok

**Comment by akguthal** [comment]
@robinamoore is the issue you're having the same as what i said?

**Comment by robinamoore** [comment]
Yes.

From what I can see all the page information has been moved into a custom field Named "fw:opt:ext:pb:page-builder:json" with the html code sat in the corresponding Value field?

**Comment by GheorgheP** [comment]
@akguthal can you provide the login details to be able to see the problem? Provide them on `pisarenco[dot]gh[at]gmail[dot]com`

**Comment by akguthal** [comment]
sorry im still new to WP, what login info should i provide / where can i get it from?

**Comment by arielzusya** [comment]
My page builder is back but not completely. It now looks like when I edit an element (such as a text box) the dropdown lists that appear on the toolbar in the visual editor don't work (like for Paragraph, Heading 1, etc. or for text color.  I can jump into the text editor and manually change formatting but that really defeats the purpose. Thoughts?
![capture](https://user-images.githubusercontent.com/25723617/29431416-182eb0e2-8355-11e7-9e8f-46d4b3269d8c.PNG)

**Comment by mtmcgreg** [comment]
When I go to a page, the information from before is there and displayed. However when I go to edit it, the information is not there so it isn't editable. As you can imagine this is a big problem. I need to be able to directly edit each page and the existing content. 

I have updated to 2.7.6

**Comment by GheorgheP** [comment]
@akguthal I needs wordpress dashboard login details.
@arielzusya, @mtmcgreg  please provide tails on `pisarenco[dot]gh[at]gmail[dot]com` too.

**Comment by mtmcgreg** [comment]
I sent

**Comment by mtmcgreg** [comment]
@GheorgheP let me know if you need anything else

**Comment by akguthal** [comment]
Just sent my credentials over but since WP is installed locally for me I'm not sure how they would be useful

**Comment by GheorgheP** [comment]
@akguthal Please then create a content backup and share the backup `.zip` to me via Google Drive.

**Comment by danyj** [comment]
@everyone who has disaperaing content issue this is how to "fix" it 


**thing to know;**   page builder and shortcodes  update is not in 


after you update Unyson   

go in updates again and click on Check again 

![screenshot_6](https://user-images.githubusercontent.com/2340172/29432810-44588100-839d-11e7-83aa-f8abb65c6233.jpg)


you will than see at the bottom of the page Unyson extensions update


click on it to update extensions ,**MOST**  important to update the page builder and shortcodes extension


![screenshot_7](https://user-images.githubusercontent.com/2340172/29432947-a99994c8-839d-11e7-993c-a93fa4e3cabd.jpg)

**Comment by robinamoore** [comment]
@danyj - thanks. Following those instructions has fixed the problem. Thank-you.

**Comment by marine207** [comment]
I have just performed the update and the issue is resolved for me!  No JS errors in console any more.  Thank you!

**Comment by GheorgheP** [comment]
@mtmcgreg Fixed by updating the extensions.

**Comment by samirosman2** [comment]
works fine thats both  @danyj  @andreiglingeanu both did a wonderful Job thanks million 💯

**Comment by akguthal** [comment]
works for me too. thanks all!

**Comment by GheorgheP** [comment]
Thank you all for being patient and responsive.
One more time big thanks to @danyj, you did Fast&Furious :rocket:

**Comment by danyj** [comment]
@GheorgheP any time, glad it worked out for all of us. Great to see and note that we all in it together.

**Comment by mtmcgreg** [comment]
I am having trouble when I am editing text within the page editor. For titles- It won't let me change from paragraph style to header 1, 2 or 3. That's within the Unyson page editor.

**Comment by GheorgheP** [comment]
@mtmcgreg Please refer this issue: https://github.com/ThemeFuse/Unyson/issues/2732

**Comment by macxb** [comment]
new update is great! I updated then forced a recheck for more updates, then updated the extentions/modules and everything is fine! Also I'm NOT having any problems with h1-h4 text sizeing, it works perfectly for me now.
Thanks for the fix!

**Comment by Kopp13** [comment]
Good for me too gj all

**Comment by mthamill** [comment]
Great, works, thanks Danyj

**Comment by gigit95** [comment]
Didn't work for me, 'I'm returning back to v. 2.6.16. Visual Page Builder is still blank after trying the danyj's solution.

**Comment by fasonera** [comment]
I´ve tried updating according to @danyj instructions but it doesn´t work. I still get a blank Page Builder and the Theme settings won´t load.  I get the error-message "cURL error 56: Recv failure: Connection reset by peer".

**Comment by ViorelEremia** [comment]
@fasonera see here https://github.com/ThemeFuse/Unyson/issues/2790

**Comment by designer201** [comment]
I am having the same issues with Unyson version 2.7.11. I just updated the theme, plugins and WP (4.9.2).  
Page builder - The content has disappeared
All Pages - All the pages are disappeared
Menus - Menus are disappeared
Please let me know how to fix these issues.
Thanks!
![screen shot 2018-02-04 at 3 44 31 pm](https://user-images.githubusercontent.com/36141235/35783958-f22670a4-09c5-11e8-8e67-2b9b63b05681.png)
![screen shot 2018-02-04 at 3 47 32 pm](https://user-images.githubusercontent.com/36141235/35783959-f246f234-09c5-11e8-82ab-20d7babcc1b7.png)
![screen shot 2018-02-04 at 3 54 17 pm](https://user-images.githubusercontent.com/36141235/35783960-f26b5552-09c5-11e8-9ab5-e4148c204219.png)

**Comment by rroots** [comment]
This does not help as I updated all before. Still same problem exists. I can let you access my dashboard to see for yourself. I attached a pdf showing all is updated. Problem still persists.

**Comment by Becca800** [comment]
Hey RRoots, try this. On the sidebar in admin, click on Unyson up at the top left (not in your plugins section). Reactivate all the extensions. Worked for me.

**Comment by rroots** [comment]
Thank you for your help. I updated that way before. The problem may be I am using XP. Think this old computer may finally be due a burial. Attached is what I see. Robert Roots- Speaker, Consultant and Author of Child Support is more than Money! (and) Success Secrets from The Three Little PigsRobertRoots.com

**Comment by Becca800** [comment]
I see what you're saying. The normal html editor is what you're not seeing. That's because you're using the Unyson editor. To the left of the black space, click default editor.

**Comment by Becca800** [comment]
However, if the page was built with the Unyson editor, you might lose the content. The Unyson editor looks much different.

**Comment by Becca800** [comment]
To edit the content of the page using Unyson, you click on any component below that area. It doesn't look like the normal editor. But if you click on, say, a text component. then up will pop a regular looking text editor with the content inside.

**Comment by Becca800** [comment]
That whole page you're showing in the other thread was built with Unyson. There is nothing wrong with it. But if you switch to the default editor, you will lose all those mods and probably the content. Besides, it's much easier using the Unyson editor once you figure it out. For example, the first thing on your home page is a section called header with a slider component. If you want to edit the slider, just click on it.

**Comment by Becca800** [comment]
Wait, I might have been looking at an image the other person you were talking to uploaded. I can't see anything you uploaded. No attachment.

**Comment by rroots** [comment]
Thanks for your assistance. The problem is the XP. No longer supported with the update. It was fine all weekend. Time to buy another computer. This one lasted for 9 years.
I appreciate the help. You are awesome. Robert Roots- Speaker, Consultant and Author of Child Support is more than Money! (and) Success Secrets from The Three Little PigsRobertRoots.com

**Comment by Becca800** [comment]
Sorry I couldn't be of more help. Good luck with getting a new computer!

**Comment by rroots** [comment]
You were great help. Let me know the problem was probably technology. Yes, new computer time and should be great sales this weekend for President's Day. Robert Roots- Speaker, Consultant and Author of Child Support is more than Money! (and) Success Secrets from The Three Little PigsRobertRoots.com

**Comment by lisa-deutscher** [comment]
Same issue here - I wanted to update some content on the page (after not checking in for about 7 months): unyson visual page builder was empty. I updated everything to the current version in the hope that would fix it - but the page builder still shows up blank, see screenshot.
The content on the front end shows up fine, but there is no chance of editing it!
Please help!
![screenshot-problem](https://user-images.githubusercontent.com/37328205/37331993-cacfdaac-26a5-11e8-80a2-21b141402616.jpg)

**Comment by ViorelEremia** [comment]
@lisa-deutscher have you tried that: https://github.com/ThemeFuse/Unyson/issues/2764#issuecomment-323189456
also try to remove any cache: browser, wordpress plugins, or server cache

**Comment by ViorelEremia** [comment]
@lisa-deutscher for old versions internet explorer we don't support anymore

**Comment by lisa-deutscher** [comment]
Hi, thanks for the reply. 
I am using Firefox, but now also tried it on Chrome. I also deleted the cache, as you suggested.
No change. :'(
More ideas?

**Comment by ViorelEremia** [comment]
Send me some temporary admin credentials: ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by lisa-deutscher** [comment]
Ah! I just saw that I overlooked your first advice "have you tried that: #2764 (comment)" 
I went through that and now it's working =D 
great, thank you!

**Comment by toddel-71** [comment]
Hello together,
after the update of Unyson 2.7.12 I have issues with my webpages. Wordpress is on the latest version. Here are some screenshots, that shows the issues:
![design-theme settings](https://user-images.githubusercontent.com/37479695/38136025-21be8774-340b-11e8-877a-d7f653474d58.jpg)
![page-example](https://user-images.githubusercontent.com/37479695/38136026-22048f58-340b-11e8-8f8c-85cabd32e417.jpg)
My theme is on the latest version and I don't know how I can fix it. I also tried to deactivate all Unyson elements and reactivate them. But still the same issue. Only a restore back to the previous version fix the issue.

**Comment by ViorelEremia** [comment]
@toddel-71 try to enable wp debug, check browser console, try to change to a default wordpress theme, some themes have their extensions disable them.

**Comment by Holocron4D** [comment]
I find the solution just checking the php version on the server and updated, minimum 5.4.

Hope this helps.
