### ISSUE TITLE
WP Mail test connection issue

### ISSUE THREAD

**Issue by DKudleichuk** [ThemeFuse/Unyson#3039]
Hello!

i can't send a test message through Contact Form, it doesn't work on latest wordpress 4.9 and latest unyson framework. When i click on "Send a test email" i get following error in console:

![2017-11-23_21-08-45](https://user-images.githubusercontent.com/1137721/33186522-cd18e984-d092-11e7-890d-f53f813f5721.png)

Could you fix an issue? Thank you so much

**Comment by DKudleichuk** [comment]
Also i have noticed that i don't receive emails through wp-mail or SMTP, it seems WP 4.9 broke something in Unyson. Could you fix this please?

**Comment by ViorelEremia** [comment]
First issue is solved see here: https://github.com/ThemeFuse/Unyson-Mailer-Extension/commit/93828a57b88d1f05394ae67bf6f74f6eed4d6235
Smtp was tested very well check your server configuration or install contact form and check if everything is fine.

**Comment by DKudleichuk** [comment]
Good evening! Thank you so much for quick fix. Regarding second problem, i used WP-mail, not SMTP. Also i installed Contact Form 7 to test, it works without issues using wp-mail, but i still can't receive emails from Unyson contact form. Is there any way how to test what happens?

Thank you again for your help

**Comment by ViorelEremia** [comment]
Hi,
we use unyson with contact form for many sites, can you drop me some temporary credentials (admin, ftp): viorel [ a ] themefuse [ dot ] com - so I can check in tomorrow morning(it's night for us now). I think you have some configuration that i can't reproduce in my end.

**Comment by DKudleichuk** [comment]
Sure! Sorry i don't want to disturb you on a weekend, will speak on Monday!
Best wishes!

**Comment by ViorelEremia** [comment]
Is your issue solved?

**Comment by DKudleichuk** [comment]
It works now, but it's strange, i did not receive emails few days ago, and i did not touch any code. Will get back if there will be more info. Thank you again!
