### ISSUE TITLE
Failed to create tmp table _fwbk_wp_commentmeta

### ISSUE THREAD

**Issue by munkhbayaryo** [ThemeFuse/Unyson#3245]
I'm getting this error when installing demo content. How to solve it guys?

Failed to create tmp table _fwbk_wp_commentmeta. COLLATION ‘utf8_general_ci’ is not valid for CHARACTER SET ‘utf8mb4’

**Comment by ViorelEremia** [comment]
Have you the latest backup extension? This issue was fixed in that commit: https://github.com/ThemeFuse/Unyson-Backups-Extension/commit/16186f8e9004ac50be2b8cdfd7c5801e09dde278

**Comment by munkhbayaryo** [comment]
@ViorelEremia Yes, I'm using latest version of extension. Still can't solve this issue :(

**Comment by ViorelEremia** [comment]
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by munkhbayaryo** [comment]
@ViorelEremia I'm using c9.io , could you just signup with this or provide registered email address? I'll add you in my project.

**Comment by ViorelEremia** [comment]
No, I can't create a ftp account and send it to my email.

**Comment by munkhbayaryo** [comment]
Ok understood, sent an email.
