### ISSUE TITLE
Critical issue above PHP version 7.2

### ISSUE THREAD

**Issue by etwordpress01** [ThemeFuse/Unyson#3526]
We have found an issue with PHP version.

With Apache/2.4.33 and PHP/7.2.7 our customers are facing issues.  When we activate Unyson plugin then error display at of site.

Warning: count(): Parameter must be an array or an object that implements Countable in E:\xampp\htdocs\www\listingo\wp-includes\post-template.php on line 284

http://prntscr.com/k9x9ga

![download](https://user-images.githubusercontent.com/31212934/43079572-e6dfee76-8ea6-11e8-92c7-85e0c188b512.png)

We checked it Twenty Seventeen theme and only one plugin( Unyson ) is active. When i deactivate Unyson plugin then it goes.

Please help me to resolve this issue. PHP 7.2 doesn't allow count(null); Might be Unyson plugin you used count for anything. 

Thanks

**Comment by danyj** [comment]
https://github.com/ThemeFuse/Unyson/issues/3095

**Comment by danyj** [comment]
https://core.trac.wordpress.org/ticket/42814

**Comment by etwordpress01** [comment]
Hi @danyj 

Thank you for quick response.

So you mean to say that issue is with PHP version and WordPress core not with Unyson?

Our customers are asking what could be the issue? What could be the solution for it? I need to ask my customers to downgrade PHP version to 7.1?

Thanks

**Comment by ViorelEremia** [comment]
Find in your code if you have the deprecated function ```create_function('$path', 'include $path;')``` and remove it; see here an example: https://github.com/ThemeFuse/Scratch-Theme/commit/6ad21caa154319fe82d9f6816b74f2355154c70e
Your issue was fixed here: https://github.com/ThemeFuse/Unyson-SEO-Extension/issues/10
Do you use the seo extension? If not then you must find in the theme functions related to this commit: https://github.com/ThemeFuse/Unyson-SEO-Extension/commit/2ce4a96447f59e473f4d74056c34c6e0860f4450

**Comment by danyj** [comment]
@etwordpress01  yes it was reported but looks like they cant come to an agreemant

**Comment by etwordpress01** [comment]
Hi @ViorelEremia 

We didn't use create_function('$path', 'include $path;'); in our theme. Yes you are right when i deactivate Unyson SEO extension then issue get resolved.

How we can resolve it, do i need to ask my client to deactivate SEO extension? Please consider this fix in next update please. 

and thank you @danyj  for help me out.

Thanks

**Comment by ViorelEremia** [comment]
@etwordpress01 have you the latest unyson seo extension?

**Comment by ViorelEremia** [comment]
I see the fix was pushed to the latest version.

**Comment by etwordpress01** [comment]
Hi @ViorelEremia 

Yes, i have updated SEO extension.  To confirm i recently deleted Unyson plugin and installed it again with new extension but issue still persist.

![download 1](https://user-images.githubusercontent.com/31212934/43130822-fef38950-8f50-11e8-97d0-baee8e250da8.png)

I think GitHub take some time to sync data? I installed and it shows version 1.0.11 while it should show 1.0.12

![screenshot_1](https://user-images.githubusercontent.com/31212934/43131012-6c103538-8f51-11e8-9393-a725787cfc0e.png)

![screenshot_2](https://user-images.githubusercontent.com/31212934/43131080-92db026a-8f51-11e8-80d5-ba6ec4259bce.png)


Thanks

**Comment by ViorelEremia** [comment]
@etwordpress01 can you:
Send me some temporary credentials (admin, ftp): ```viorel@themefuse.com```
Please provide a link to this thread when submitting the message.

**Comment by etwordpress01** [comment]
Hi @ViorelEremia 

I don't have live URL, i am testing it at my local PC with PHP version 7.2.7 

I reinstall SEO extension and Now i get latest Version 1.0.12

![screenshot_3](https://user-images.githubusercontent.com/31212934/43131948-ba7ded08-8f53-11e8-8885-a0294e107bc0.png)

issue is still there. I installed latest version of xampp with PHP version 7.2.7

https://www.apachefriends.org/download.html

Thanks

**Comment by ViorelEremia** [comment]
Then try to inspect yourself what is happening in this file: unyson/framework/extensions/seo/class-fw-extension-seo.php
the function ```_theme_action_update_seo_tags``` first of all remove the entire body of the function and check in the frontend if everything is fine if yes then the error is in this function add back the code and remove some casese from rthe switch and again check the fronened and so on.

**Comment by etwordpress01** [comment]
@ViorelEremia 
I think i found a issue. I think issue is with wp_trim_excerpt( $post->post_content ); Error comes when no content found. I mean when we give null value to wp_trim_excerpt
Might i am wrong. Could you please confirm it?

I tried to add some content in page and then everything start working.

This should 
$this->seo_tags['excerpt']['value']      =  ! empty( $post->post_excerpt ) ? get_the_excerpt() : wp_trim_excerpt( $post->post_content );

be  as

$this->seo_tags['excerpt']['value']      =  ! empty( $post->post_content ) ? wp_trim_excerpt( $post->post_content ) : '';

I am not sure if i am wrong. Please confirm it.
 
Thanks

**Comment by ViorelEremia** [comment]
Try my last commit. On my server also it is 7.2 version but there are no errors with or no content.

**Comment by Bilyachenko** [comment]
@ViorelEremia 

Your last commit fix problem

**Comment by Bilyachenko** [comment]
Is have wait update for SEO extensions ?
