### ISSUE TITLE
Deprecated in PHP 7.4

### ISSUE THREAD

**Issue by PeymanNaeimi** [ThemeFuse/Unyson#3915]
I have these errors in PHP 7.4 :
----------------------------------------------------

Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\wp-content\plugins\unyson\framework\includes\option-types\wp-editor\includes\class-fw-wp-editor-settings.php on line 192

Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\wp-content\themes\...\unyson\extensions\builder\includes\option-types\builder\extends\class-fw-option-type-builder.php on line 353

Deprecated: Function get_magic_quotes_gpc() is deprecated in ...\wp-content\plugins\unyson\framework\helpers\general.php on line 487

----------------------------------------------------
my PHP -v informations:

PHP 7.4.2 (cli) (built: Jan 21 2020 17:52:43) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by ViorelEremia** [comment]
It is fixed in the latest version, update the plugin

**Comment by Saxtone** [comment]
Hello,

Thank you for the fix on the deprecated functions. Unfortunately I still receive the second deprecated error with the latest plugin version:

Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\wp-content\themes...\unyson\extensions\builder\includes\option-types\builder\extends\class-fw-option-type-builder.php on line 353

From the commit history on top, I can't find that this line has been edited 👀

**Comment by jonmlas** [comment]
I also got this on PHP 7.4

Deprecated:  Array and string offset access syntax with curly braces is deprecated in /nas/content/live/xxxxxx/wp-content/plugins/unyson/framework/extensions/builder/includes/option-types/builder/extends/class-fw-option-type-builder.php

**Comment by vtamm** [comment]
Same here on PHP 7.4.9:

`Deprecated: Array and string offset access syntax with curly braces is deprecated in /Users/vtamm/Sites/thomaseklof/web/app/plugins/unyson/framework/extensions/builder/includes/option-types/builder/extends/class-fw-option-type-builder.php on line 353`

**Comment by maxjutras** [comment]
This issue was fixed for PHP 7.4 but now cause a Fatal error in PHP 8

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /includes/Unyson/framework/includes/option-types/wp-editor/includes/class-fw-wp-editor-settings.php on line 192

Any idea?

Thanks a lot

**Comment by macdonjo** [comment]
I think Unyson is abandoned and no longer maintained.
