### ISSUE TITLE
Pages opening in "Default Editor", Visual Page Builder broken

### ISSUE THREAD

**Issue by Dorf** [ThemeFuse/Unyson#424]
Some pages that were built with the Visual Page Builder now open in "Default Editor" mode. 

When I switch to VPB there is only a single *Text Block* element that contains all of the VPB code starting with *[section is_fullwidth="" ...*

Please advise, gracias!

![vpb-issue](https://cloud.githubusercontent.com/assets/490985/6977973/27ae25d2-d986-11e4-8d90-fc9402cfc786.png)

**Comment by duongancol** [comment]
I have same issue, it's very confuse

**Comment by RayNguyen** [comment]
Same issue here, not all pages, but almost.
Any helps would be appreciated. Thanks.

**Comment by flody** [comment]
It's exactly the behavior we've got here after trying to applied a revision.
Could it be related to this issue?
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/issues/26

**Comment by GheorgheP** [comment]
Hi,

I'm investigating this problem now. Could you provide one ore more scenarios, to be able to get this issue too?

**Comment by RayNguyen** [comment]
I don't remember exactly how I got this issue, just installing latest version and everything worked well (no error, no warning, etc ...), but then when I tried to edit pages, the issue came.
Any helps would be appreciated. Thanks.

**Comment by Dorf** [comment]
My client adds their own content, and didn't mention any distinct trigger. You are welcome to whatever access you need, just let me know how to get it to you

**Comment by flody** [comment]
Hello,

A simple scenario is to go to revision and to apply a previous revision.

**Comment by GheorgheP** [comment]
I will investigate this problem, and solve as fast as possible.

**Comment by duongancol** [comment]
@GheorgheP : because I had problem with demo install , I decided to use wordpress importer, when I checked page that imported from wordpress importer. it look like this:
![screen shot 2015-04-09 at 2 17 39 pm](https://cloud.githubusercontent.com/assets/1773011/7062031/4e0fc356-dec3-11e4-9ec2-db61b781368e.png)
![screen shot 2015-04-09 at 2 17 46 pm](https://cloud.githubusercontent.com/assets/1773011/7062032/5016a5d4-dec3-11e4-838a-6315d2e1feae.png)
Just see text block shortcode when click Visual Page Builder

**Comment by GheorgheP** [comment]
Hi,

Sorry for big delay. Could you provide the XML file you imported, to be ale to test in it?

**Comment by duongancol** [comment]
ok, what is your email?

**Comment by xpeeder** [comment]
I am  also facing same issue. 
Today i am work with section shortocde. and just refresh the page. i saw  default editor showing with junk code. when i click to visual page editor. saw my section code removed and showing a text block.

i thing this issue with section. cause last 2 days i work with section and column. i faced this issue 3 times. today just work with section. and just add a text block to see frontend changes. saw its broken after refresh.

I thing this is a major issue for everyone here. it will be great if your team fix this asap. :)

Thank you

**Comment by xpeeder** [comment]
Also we saw this page metabox field also reset :/  is this from any connection issue ??

Thanks

**Comment by GheorgheP** [comment]
For @duongancol,

Here's the email address: dev-team@unyson.io

**Comment by danyj** [comment]
Same thing happened just now,  I  pasted latest masters  shortcode + builder ,  simple copy paste

**Comment by danyj** [comment]
Deleted shortcode and builder via unyson remove , reinstalled  them , same bug 

Deleted unyson , installed again , installed extensions , same issue
http://prntscr.com/6uyexq

**Comment by Chrislynchdesign** [comment]
Hi. I've had the same issue twice now. Once when I made a revision and the second time when I logged in and out or WP. Any chance you'll be updating soon with a fix! Please please please!

**Comment by danyj** [comment]
ok , this one is somehow connected to this  method
https://github.com/ThemeFuse/Unyson-PageBuilder-Extension/blob/1bfd3147baa19f1911c0910f2ca4ea76e06932e0/class-fw-extension-page-builder.php#L154


what I noticed is when you see the bug in backend , your frontend will remove div  class name 

    fw-page-builder-content


and instead it will print 2 paragraphs , one instead of the 

    <div class="fw-page-builder-content"...

and another in place of fw-page-builder-content  div closing


note that I did not save at all, just did page refresh, saw the bug , checked frontend and that is what I got

**Comment by xpeeder** [comment]
its also reset metabox settings.
now i faced same issue again.  i saw metabox field also reset. and visual editor broken with junk code.

**Comment by xperter** [comment]
I believe this is the major issue now in unyson. 
@moldcraft  @valeriuzdrobau it will be great if your team take care this issue

**Comment by Chrislynchdesign** [comment]
I agree with xperter. My websites and one page design so this is creating hudge amounts for work for me. I love the plugin, but this is a real issue.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/424#issuecomment-95023698

@GheorgheP is investigating this a few days.

**Comment by GheorgheP** [comment]
https://github.com/ThemeFuse/Unyson/commit/c75eca301336977b4c9fb33dc746320ddfff2a5c

**Comment by ankitaraikundalia** [comment]
Hi,

I faced a similar issue on browser hang. While working on a page, my browser got hanged and I closed it from task manager. On opening the page again, it looks fine on front-end, but in back-end, I can see only one text element with all the shortcode in it.

**Comment by ecanziba** [comment]
Any idea how to fix this. The first time that I have a nightmare with my clients in 8 years, and just because I started using this page builder instead of the old ones, it displays the shortcodes on default editor, but when I switch back on Visual Page Builder, all the content is inside the Text Block. Do not get me wrong, I loved this plugin, but this is a real issue, and it is active for more than 3 months.

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/424#issuecomment-132275588

1. Do you have the latest version of Unyson?
2. Extensions are up-to-date?
3. Do you have automatic plugin updates enabled on your server?
4. Can you restore the pages with this problem from revisions?

**Comment by ecanziba** [comment]
Yes all of this point are Up to Date. But still the same problem with shortcodes of Page Builder (Page Builder Shortcodes) . It happened only on few pages, where they have HTML included inside the pages withing Text Block, and after Updating the Plugin, it appeared the problem.

**Comment by moldcraft** [comment]
> after Updating the Plugin, it appeared the problem

You updated the plugin manually or it was updated automatically?

----

Anyway, how to reproduce this problem?

**Comment by ecanziba** [comment]
Where can I add the Visual Page Builder Shortcode, to have the same structure again ? 

To not display the all shortcode inside a TEXT BLOCK, but I need it to display all the Sections and other Elements inside Page Builder as it was at beginning.

**Comment by moldcraft** [comment]
> Yes all of this point are Up to Date

The it's a Yes for: Can you restore the pages with this problem from revisions?

Then just restore the page from revisions and that's all.

> Where can I add the Visual Page Builder Shortcode, to have the same structure again ?

Do you want to convert shortcode string to page builder elements? It's impossible.

**Comment by mbtocalli** [comment]
I recently move my website from localhost to an online host and now I have the same problem stated in this post. All my post build with the visual builder shows one block of code in the default editor, and when and switch to visual builder it shows the same code in a single "text block" element.
Is there any solution to this issue?

**Comment by moldcraft** [comment]
> I recently move my website from localhost to an online host

Which tools have you used for that?

**Comment by Ataurr** [comment]
@mbtocalli  You can try this way to move your site https://vimeo.com/115331137

**Comment by llemurya** [comment]
@Ataurr make this video public, because now it is private and other users can't see it.

**Comment by mbtocalli** [comment]
manual file migration by FTP and manual change of URL in database. Then uploading database with phpmyadmin,

**Comment by mbtocalli** [comment]
Ataurr, that video is private. I cannot see it.

**Comment by moldcraft** [comment]
@mbtocalli Try to migrate your localhost content to live site using Backup & Demo Content extension, create a demo install bundled in theme http://manual.unyson.io/en/latest/extension/backups/index.html#demo-content-install

**Comment by mbtocalli** [comment]
I guess now that I have deleted the original version can't use the backup extension. (The original version was uploaded in a temporary folder in the online server)

**Comment by moldcraft** [comment]
> https://github.com/ThemeFuse/Unyson/issues/424#issuecomment-97451477 While working on a page, my browser got hanged and I closed it from task manager.

[This problem was fixed](https://github.com/ThemeFuse/Unyson/issues/859)

----

https://wordpress.org/support/topic/all-layout-elements-now-are-inside-a-text-block?replies=12#post-8183238

**Comment by TCQTheConseQuor** [comment]
hello, @moldcraft , the error still stands, as i wrote it at https://github.com/ThemeFuse/Unyson/issues/553 too. Do you have any suggestion, how can be it resolved?
We tried move data with backup & demo content and manually too, with the same result.

**Comment by moldcraft** [comment]
with backup & demo content you did this?

1. Create Content Backup
2. Download the zip
3. Upload the zip on another site/server in wp-content/uploads/fw-backup
4. Do Restore

**Comment by TCQTheConseQuor** [comment]
hello, @moldcraft, yes we did this way, and also we tried manually move the db, both has the same result.
Also, now, sometimes, when we editing a post / page for a longer time, e.g. 1-2 hours, vpb just crashes, basic editor appears with shortcodes, and we have to restore from previous revision, to reactivate the page editor normal usage.

**Comment by moldcraft** [comment]
How to reproduce/test the problem?

**Comment by TCQTheConseQuor** [comment]
Hello, @moldcraft, you mean reproduce, e.g. such as to get an account to the site, or the backup files?

At this moment, we have more problems with the VPB, like sliders doesn't appears (missing population method, or frontend appearance problem), old posts became unaccessable after move the site from server to server (we tried multiple migration / backup tools)
And double checked the DB and the filesystem, they are matching.

**Comment by moldcraft** [comment]
@TCQTheConseQuor our and other themes uses Demo Content Install and everything is imported without any issue. So I am thinking that you are doing something wrong. Can you give me admin/ftp access to your site and I will try to do the import?

**Comment by TCQTheConseQuor** [comment]
We updated all missworking posts and sliders manually, as i wrote above, and this solved the problem.
We didn't tried to find out, why was enough to copy db field content to notepad and back to the same field, but it was, so we're glad, we finished it, and now everything works well.

**Comment by mattstrt67** [comment]
I've come across this same issue - it happened when I updated WP from 4.8.1 to 4.8.2. I restored the site from a backup before the update and it worked, when I tried the update again it broke. 

Is there something I am missing? Maybe a setting that toggles off for the visual page builder when wp is updated?

**Comment by swosmax** [comment]
Same problem here :( WP 4.8.2 Unyson 2.7.7 all extentions updated.
All works fine and suddenly issue. When I add some components in Visual Page Builder and save then everything ok, but when O only change for Default text edition then all components disapear.. only text block remain. Revision then also is broken :( Is there any good solution?

**Comment by mattstrt67** [comment]
Back up and then Try Disabling Unyson and Re-enabling. If that doesn’t work, let me know.

**Comment by davepoon** [comment]
![image](https://user-images.githubusercontent.com/138992/40697895-bef593fa-640f-11e8-837d-50ec71af3cc0.png)

I tried. Deactivated and reactivated the Unyson plugin, still the same.
Only showing the Text Block content elements in the visual page builder.

![image](https://user-images.githubusercontent.com/138992/40697959-0974fc40-6410-11e8-8489-bd298cd88716.png)
And only showing the html code in the default editor.

**Comment by davepoon** [comment]
Any tricks that I can get my layout and content back?

**Comment by mattstrt67** [comment]
If you have an easily accessible backup, you can try two more things... 

1. Restore your site to the previous version of WordPress until Unyson releases their new update. (Not recommended unless the site is strictly in development mode due to security reasons).

2. Delete the Unyson plugin and reinstall it completely. You will have to reactivate all of the plugin add ons in the Unyson tab. 

Be sure to use something like updraft plus for backups. 

Once done, try logging in through incognito to make sure there aren’t any caching errors.

Good luck!

**Comment by davepoon** [comment]
I tried the second option, still the same problem unfortunately.
I had to take another 3 hours to recreate the page again...
And I have to take a full backup using updraft plus every 30mins, in case I gonna lose my work again.

Thank you so much for your help @mattstrt67 
Hopefully Unyson can fix this critique issue soon.

BTW, to replicate this issue, you can try the following,
1. Create a layout using Unyson for a page.
2. Save your changes a few times.
3. Restore one of your previous revision.
4. And your layout will be gone. Only showing the Text Block content element in the Visual Page Builder mode.
